[project]
name = "weathercli"
version = "0.1.0"
description = "CLI tool to get weather information."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "click"
]

[project.scripts]
weathercli = "weathercli.cli:cli"

[tool.setuptools.packages.find]
where = ["src"]
